### ISSUE TITLE
Duplicate

### ISSUE THREAD

**Issue by shinnn** [passy/purescript-bin#1]
Sorry I created [node-purescript-bin](https://github.com/purescript-contrib/node-purescript-bin) a little earlier ([2015/03/22](https://github.com/purescript-contrib/node-purescript-bin/commit/9924b7fb897dba6ec4f40bca9c9a37303092590a)). It's published as [`purescript`](https://www.npmjs.com/package/purescript) to npm, [recommended in the purescript website](http://www.purescript.org/download/) and officially maintained by [purescript-contrib](https://github.com/purescript-contrib) team.

**Comment by passy** [comment]
@shinnn Ohh, that's great! We must have been in a race condition where I checked for the existence of something like this when it didn't exist and actually started working on it after you released it. I'll update my repo accordingly and link to yours instead. :)

**Comment by shinnn** [comment]
@passy Thanks!
